# Generated by Django 6.0.6 on 2026-07-03 04:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_winners', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LOCKED', 'Locked'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditors', models.ManyToManyField(blank=True, help_text='Auditors assigned to this election (max 3)', related_name='elections_as_auditor', to=settings.AUTH_USER_MODEL)),
                ('electoral_officer', models.ForeignKey(blank=True, help_text='Electoral officer assigned to manage this election', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections_as_officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VOTE_CAST', 'Vote Cast'), ('SESSION_CREATED', 'Session Created'), ('SESSION_INVALIDATED', 'Session Invalidated'), ('ELECTION_LOCKED', 'Election Locked'), ('ELECTION_ACTIVATED', 'Election Activated'), ('ELECTION_CLOSED', 'Election Closed'), ('FRAUD_ATTEMPT', 'Fraud Attempt')], max_length=30)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='elections.election')),
            ],
        ),
    ]
